- hosts: all
  tasks:
    - name: esnure python3-flask is installed
      package:
        name: python3-flask
    - name: ensure /home/vagrant/my-app is a dir
      ansible.builtin.file:
        path: /home/vagrant/my-app
        state: directory
    - name: ensure app.py file is in /home/vagrant/m-app/
      ansible.builtin.copy:
        src: app.py
        dest: /home/vagrant/m-app/

    - name: ensure my-app.service file is in /etc/systemd/system/
      ansible.builtin.copy:
        src: my-app.service
        dest: /etc/systemd/system/

    - name: ensure to reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: ensure my-app is started
      ansible.builtin.service:
        name: my-app
        state: started
