- hosts: all
  tasks:
    - name: esnure tomcat is present
      package:
        name: tomcat9
    - name: ensure service is started
      service:
        name: tomcat9
        state: started
        enabled: true
    - name: Copy file
      ansible.builtin.copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/
